# Generated by Django 5.1.1 on 2026-01-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
