# Generated by Django 5.1.1 on 2026-01-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingservice',
            name='supported_devices',
            field=models.CharField(default='smartphone', max_length=250),
        ),
    ]
