# Generated by Django 5.1.1 on 2026-01-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_streamingservice_supported_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingservice',
            name='per_month',
            field=models.BooleanField(default=True),
        ),
    ]
